export { default as LOGO } from './images/logo.png';
export { default as JOB_OFFER } from './images/job-offer.png';
export { default as PROFILE } from './images/profile.svg';
export { default as PHONE } from './images/phone_outline.svg';
export { default as COPY } from './images/copy.svg';
export { default as SEARCH } from './images/search.svg';
export { default as TICK } from './images/tick.svg';
export { default as UPLOAD } from './images/upload.svg';
export { default as APPLICANTS } from './images/application.png';
